services:
  fornecedor-v1:
    build:
      context: ./fornecedor-v1
      dockerfile: dockerfile
    restart: always

  fabrica-v1:
    build:
      context: ./fabrica-v1
      dockerfile: dockerfile
    restart: always

  almoxarifado-v1:
    build:
      context: ./almoxarifado-v1
      dockerfile: dockerfile
    restart: always