services:
  fornecedor:
    build:
      context: ./fornecedor-v1
      dockerfile: dockerfile
    restart: always

  fabrica:
    build:
      context: ./fabrica-v1
      dockerfile: dockerfile
    restart: always

  almoxarifado:
    build:
      context: ./almoxarifado-v1
      dockerfile: dockerfile
    restart: always