services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672    #amqp
      - 15672:15672  #http
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rabbitsd

  fornecedor:
    build:
      context: ./fornecedor
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./fornecedor:/app
    depends_on:
      rabbitmq:
          condition: service_healthy
    networks:
      - rabbitsd

  fabrica1:
    build:
      context: ./fabrica1
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./fabrica1:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitsd

  fabrica2:
    build:
      context: ./fabrica2
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./fabrica2:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitsd

  almoxarifado:
    build:
      context: ./almoxarifado
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./almoxarifado:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitsd
  
  deposito:
    build:
      context: ./deposito
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./deposito:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitsd

networks:
  rabbitsd:
    driver: bridge